FROM php:7.4.10

RUN apt-get update
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev libonig-dev zlib1g-dev libzip-dev zip unzip nano libxml2-dev libmagickcore-dev libmagickwand-dev imagemagick libheif1 libheif-dev ghostscript cron
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install json
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip
RUN docker-php-ext-install xml
RUN pecl install imagick && docker-php-ext-enable imagick

COPY docker/php.ini /usr/local/etc/php/php.ini
COPY docker/policy.xml /etc/ImageMagick-6/policy.xml

RUN touch /var/log/cron.log
COPY docker/crontab /etc/crontab
RUN chmod 755 /etc/crontab
COPY docker/cron-loop.sh /usr/bin/cron-loop.sh

WORKDIR /var/www/html
CMD /usr/bin/cron-loop.sh
