[program:queue]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --max-time=3600 --timeout=600
directory=/var/www/html
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue_%(process_num).log
#stdout_logfile_maxbytes=0
numprocs=3
autostart=true
autorestart=true

